name: CI

on:
  push:
    branches:
      - '**'  # triggers on all branches for every commit

jobs:
  test:
    name: Run Foundry Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Foundry dependencies
        run: forge install 

      - name: Run Forge Tests
        run: forge test --ffi -vvv

  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  slither:
    name: Run Slither
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Slither
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install slither-analyzer

      - name: Run Slither
        run: slither . --exclude-dependencies