name: CI

on:
  push:
    branches:
      - '**'  # triggers on all branches for every commit

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@v1


      - name: Install Foundry dependencies
        run: forge install
      
      - name: Install OpenZeppelin Contracts
        run: forge install OpenZeppelin/openzeppelin-contracts --no-commit

      - name: Run Forge tests
        run: forge test --ffi -vvv

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Slither for Foundry
        uses: crytic/slither-action@v0.3.0
        with:
          target: "."
          sarif: results.sarif
          slither-args: --filter-paths "./lib|./test-foundry" # exclude other contracts (open zeppelin ones) and test
      - name: Upload static anaylisis SARIF output file # it should also add relevant comments on PR
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}